// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace TwilightImperiumMasterCompanion.Core.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UIStrings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIStrings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("TwilightImperiumMasterCompanion.Core.Resources.UIStrings", typeof(UIStrings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string TwilightImperiumCompanion {
            get {
                return ResourceManager.GetString("TwilightImperiumCompanion", resourceCulture);
            }
        }
        
        internal static string RaceSelection {
            get {
                return ResourceManager.GetString("RaceSelection", resourceCulture);
            }
        }
        
        internal static string UnitReference {
            get {
                return ResourceManager.GetString("UnitReference", resourceCulture);
            }
        }
        
        internal static string Purchase {
            get {
                return ResourceManager.GetString("Purchase", resourceCulture);
            }
        }
        
        internal static string BaronyOfLetnev {
            get {
                return ResourceManager.GetString("BaronyOfLetnev", resourceCulture);
            }
        }
        
        internal static string ClanOfSaar {
            get {
                return ResourceManager.GetString("ClanOfSaar", resourceCulture);
            }
        }
        
        internal static string EmiratesOfHacan {
            get {
                return ResourceManager.GetString("EmiratesOfHacan", resourceCulture);
            }
        }
        
        internal static string MentakCoalition {
            get {
                return ResourceManager.GetString("MentakCoalition", resourceCulture);
            }
        }
        
        internal static string NaaluCollective {
            get {
                return ResourceManager.GetString("NaaluCollective", resourceCulture);
            }
        }
        
        internal static string NekroVirus {
            get {
                return ResourceManager.GetString("NekroVirus", resourceCulture);
            }
        }
        
        internal static string SardakkN_orr {
            get {
                return ResourceManager.GetString("SardakkN'orr", resourceCulture);
            }
        }
        
        internal static string UniversitiesOfJol_Nar {
            get {
                return ResourceManager.GetString("UniversitiesOfJol-Nar", resourceCulture);
            }
        }
        
        internal static string Winnu {
            get {
                return ResourceManager.GetString("Winnu", resourceCulture);
            }
        }
        
        internal static string XxchaKingdom {
            get {
                return ResourceManager.GetString("XxchaKingdom", resourceCulture);
            }
        }
        
        internal static string YssarilTribes {
            get {
                return ResourceManager.GetString("YssarilTribes", resourceCulture);
            }
        }
        
        internal static string BrotherhoodOfYin {
            get {
                return ResourceManager.GetString("BrotherhoodOfYin", resourceCulture);
            }
        }
        
        internal static string EmbersOfMuaat {
            get {
                return ResourceManager.GetString("EmbersOfMuaat", resourceCulture);
            }
        }
        
        internal static string GhostsOfCreuss {
            get {
                return ResourceManager.GetString("GhostsOfCreuss", resourceCulture);
            }
        }
        
        internal static string Arborec {
            get {
                return ResourceManager.GetString("Arborec", resourceCulture);
            }
        }
    }
}
